<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting" />
    <ProjectReference Include="..\SCADA.Core\SCADA.Core.csproj" />
    <ProjectReference Include="..\SCADA.Drivers.Abstractions\SCADA.Drivers.Abstractions.csproj" />
    <ProjectReference Include="..\SCADA.Drivers.Simulator\SCADA.Drivers.Simulator.csproj" />
    <ProjectReference Include="..\SCADA.Historian\SCADA.Historian.csproj" />
  </ItemGroup>

  <PropertyGroup>
  </PropertyGroup>

</Project>
