<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <ApplicationManifest>app.manifest</ApplicationManifest>
    </PropertyGroup>

    <ItemGroup>
        <Folder Include="Models\" />
        <AvaloniaResource Include="Assets\**" />
        <ProjectReference Include="..\SCADA.Runtime\SCADA.Runtime.csproj" />
        <ProjectReference Include="..\SCADA.Graphics\SCADA.Graphics.csproj"/>
        <ProjectReference Include="..\SCADA.Drivers.Simulator\SCADA.Drivers.Simulator.csproj"/>
        <None Include="TestProject\**" CopyToOutputDirectory="PreserveNewest" />
        <None Include="Symbols\**" CopyToOutputDirectory="PreserveNewest" />

    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Avalonia" />
        <PackageReference Include="Avalonia.Desktop" />
        <PackageReference Include="Avalonia.Themes.Fluent" />
        <PackageReference Include="Avalonia.Fonts.Inter" />
        <PackageReference Include="AvaloniaUI.DiagnosticsSupport">
            <IncludeAssets Condition="'$(Configuration)' != 'Debug'">None</IncludeAssets>
            <PrivateAssets Condition="'$(Configuration)' != 'Debug'">All</PrivateAssets>
        </PackageReference>
        <PackageReference Include="CommunityToolkit.Mvvm" />
        <PackageReference Include="FluentIcons.Avalonia" />
        <PackageReference Include="Microsoft.Extensions.Hosting" />
    </ItemGroup>
</Project>
