<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SCADA.Drivers.Modbus\SCADA.Drivers.Modbus.csproj" />
    <ProjectReference Include="..\SCADA.Drivers.Simulator\SCADA.Drivers.Simulator.csproj" />
    <ProjectReference Include="..\SCADA.Package\SCADA.Package.csproj" />
    <ProjectReference Include="..\SCADA.Runtime\SCADA.Runtime.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

</Project>
