<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\SCADA.Drivers.Abstractions\SCADA.Drivers.Abstractions.csproj" />
    <ProjectReference Include="..\SCADA.Core\SCADA.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FluentModbus" />
  </ItemGroup>

  <PropertyGroup>
  </PropertyGroup>

</Project>
